name: Chrome Automated Build with .Net Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: szenius/set-timezone@v2.0
      with:
        timezoneWindows: "AUS Eastern Standard Time"
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/*.json"]'
      env:
        browser: ChromeHeadless
    - name: Build
      run: dotnet build --no-restore
    - name: Install Playwright Browser
      shell: pwsh
      run: ${{ github.workspace }}\PlaywrightDemo\bin\Debug\net9.0\playwright.ps1 install chromium
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        path: |
              PlaywrightDemo/Logs*
        if-no-files-found: warn
